Repository Microcervejaria/Microcervejaria-App, pull requests merged in 2020-11, with the labels that each got.

#29 Adicionando o gerenciar receitas(Adicionar/Editar/Remover)
  package-lock.json
  package.json
  src/assets/icons/brazing.svg
  src/assets/icons/coldThermometer.svg
  src/assets/icons/cookBookForm.svg
  src/assets/icons/description.svg
  src/assets/icons/fire.svg
  src/assets/icons/hotThermometer.svg
  src/assets/icons/plus.svg
  src/assets/icons/trash.svg
  src/assets/icons/warm.svg
  src/components/RecipeCard/index.js
  src/components/RecipeForm/index.js
  src/components/RecipeForm/styles.js
  src/pages/RecipeForm/index.js
  src/pages/RecipeForm/styles.js
  src/routes/index.js
  src/services/api.js
Labels: História de Usuário

#23 Cria tela de limpeza
  src/assets/icons/addEditRecipe.svg
  src/assets/icons/bucket.svg
  src/assets/icons/cleaning.svg
  src/assets/icons/play.svg
  src/components/RecipeCard/index.js
  src/components/RecipeForm/index.js
  src/pages/Cleaning/index.js
  src/pages/Cleaning/styles.js
  src/pages/Main/index.js
  src/pages/QRCodeReader/index.js
  src/pages/RecipeForm/index.js
  src/routes/index.js
Labels: Tela

#24 Cria modal para confirmação
  src/assets/icons/alert.svg
  src/assets/icons/interrogation.svg
  src/components/Modal/index.js
  src/components/Modal/styles.js
Labels: padronização de estilo

#31 Adiciona notificação para etapa de limpeza
  app.json
  package-lock.json
  package.json
  src/assets/images/HomeBeerIcon.png
  src/pages/Cleaning/index.js
  src/pages/Main/index.js
Labels: notificações

#34 Adiciona a tela de processos
  package-lock.json
  package.json
  src/assets/icons/clockProcess.svg
  src/assets/icons/graphBew.svg
  src/assets/icons/stop.svg
  src/assets/icons/thermometerProcess.svg
  src/components/Processes/Boil.js
  src/components/Processes/Brew.js
  src/components/Processes/InformationCard.js
  src/components/Processes/Warm.js
  src/components/Processes/styles.js
  src/contexts/auth.js
  src/pages/Main/index.js
  src/pages/Process/index.js
  src/pages/Process/styles.js
  src/routes/index.js
  src/services/auth.js
Labels: História de Usuário, Tela
